"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {Building2,Check,RefreshCw,ShieldCheck} from "lucide-react";
import {requestJson,errorMessage} from "@/lib/client-api";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {DorniBrand} from "@/components/dorni-brand";
type Organization={id:string;name:string;type:string;status:string;institutional_enabled:boolean;entitlements:string[]};
type Overview={organizations:Organization[]};
const permissions=["ORG_MEMBER_VIEW","ORG_MEMBER_INVITE","ORG_MEMBER_SUSPEND","ORG_ROLE_ASSIGN","ORG_AUDIT_VIEW","ORG_REPORT_VIEW","VEHICLE_MOVE_REQUEST"];
const labels:Record<string,string>={ORG_MEMBER_VIEW:"عرض الموظفين",ORG_MEMBER_INVITE:"دعوة موظف",ORG_MEMBER_SUSPEND:"تعليق الموظفين",ORG_ROLE_ASSIGN:"إدارة الأدوار",ORG_AUDIT_VIEW:"عرض التدقيق",ORG_REPORT_VIEW:"عرض التقارير",VEHICLE_MOVE_REQUEST:"طلب تحريك مركبة"};
export default function AdminInstitutionsPage(){const [data,setData]=useState<Overview|null>(null),[drafts,setDrafts]=useState<Record<string,string[]>>({}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState("");const load=useCallback(async()=>{try{const next=await requestJson<Overview>("/api/admin/overview");setData(next);setDrafts(Object.fromEntries(next.organizations.map(o=>[o.id,o.entitlements])));setError("");}catch(e){setError(errorMessage(e));}},[]);useEffect(()=>{void load();},[load]);async function save(org:Organization,enabled:boolean){setBusy(org.id);setError("");try{await requestJson(`/api/admin/institutions/${org.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({enabled,entitlements:enabled?(drafts[org.id]??[]):[]})});setNotice(enabled?`تم تفعيل ${org.name} كمؤسسة موثقة.`:`تم تعطيل الصلاحيات المؤسسية لـ${org.name}.`);await load();}catch(e){setError(errorMessage(e));}finally{setBusy("");}}if(!data)return <main className="loading-screen" dir="rtl">{error?<p>{error}</p>:<><RefreshCw className="spin"/> جاري تحميل المؤسسات…</>}</main>;return <main className="admin-control" dir="rtl"><aside className="admin-control-sidebar"><DorniBrand href="/admin"/><nav><Link href="/admin">لوحة الإدارة</Link><Link href="/admin/institutions">المؤسسات الموثقة</Link></nav></aside><section className="admin-control-main"><header><div><p>صلاحيات تتحكم فيها دورني</p><h1>إدارة المؤسسات الموثقة</h1></div></header><div className="admin-control-content">{error&&<p className="form-error">{error}</p>}{notice&&<p className="success-banner"><Check/> {notice}</p>}<section className="partner-review-list">{data.organizations.map(org=><article className="partner-review-card" key={org.id}><div className="partner-review-head"><div><span className="partner-avatar"><Building2/></span><div><h2>{org.name}</h2><p>{org.type} • حالة الحساب: {org.status}</p></div></div><Badge>{org.institutional_enabled?"مؤسسة مفعّلة":"غير مفعّلة"}</Badge></div><div className="permission-list"><h3><ShieldCheck/> تخويلات المؤسسة</h3>{permissions.map(permission=><label key={permission}><input type="checkbox" disabled={org.status!=="ACTIVE"} checked={(drafts[org.id]??[]).includes(permission)} onChange={e=>setDrafts(current=>({...current,[org.id]:e.target.checked?[...(current[org.id]??[]),permission]:(current[org.id]??[]).filter(x=>x!==permission)}))}/>{labels[permission]}</label>)}</div><div className="partner-review-actions"><Button disabled={busy===org.id||org.status!=="ACTIVE"} onClick={()=>void save(org,true)}><Check/> تفعيل وحفظ التخويلات</Button>{org.institutional_enabled&&<Button variant="outline" disabled={busy===org.id} onClick={()=>void save(org,false)}>تعطيل مؤسسي</Button>}</div></article>)}</section></div></section></main>}
