"use client";
/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-location-assign-relative-destination, @next/next/no-img-element */
import { useCallback,useEffect,useMemo,useState } from "react";
import QRCode from "qrcode";
import { Bell,BookOpen,CarFront,Check,CircleUserRound,Copy,Headphones,LogOut,Menu,Plus,QrCode,RefreshCw,Settings,ShieldCheck,X } from "lucide-react";
import { DorniBrand } from "@/components/dorni-brand";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { WebMcpTools } from "@/components/webmcp-tools";

type Code={id:string;serial_number:string;public_token:string;activation_state:string};
type Vehicle={id:string;manufacturer:string;model:string;color:string;nickname?:string|null;year?:number|null;code_assignments?:{ended_at:string|null;codes:Code|null}[]};
type Report={id:string;report_type_code:string;status:string;owner_response:string|null;duplicate_count:number;created_at:string;vehicles:{manufacturer:string;model:string;color:string}|null};
type Me={user:{id:string;phone:string};profile:{account_status:string};vehicles:Vehicle[];reports:Report[];contacts:unknown[];preferences:{primary_channel:string}};
const reportLabel:Record<string,string>={BLOCKING_EXIT:"السيارة تعيق خروجي",PLEASE_MOVE:"الرجاء تحريك السيارة",LIGHTS_ON:"الأنوار ما زالت شغّالة",DOOR_OR_WINDOW_OPEN:"باب أو نافذة مفتوحة",VEHICLE_DAMAGE:"هناك ضرر بالسيارة",URGENT_ATTENTION:"تنبيه عاجل"};
const activeCode=(v:Vehicle)=>v.code_assignments?.find(a=>!a.ended_at)?.codes??null;

export default function OwnerApp(){
  const [data,setData]=useState<Me|null>(null),[tab,setTab]=useState<"account"|"alerts"|"vehicles">("vehicles"),[menu,setMenu]=useState(false),[panel,setPanel]=useState<"support"|"guide"|"privacy"|"settings"|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState({manufacturer:"",model:"",color:"",year:""}),[claim,setClaim]=useState({serialNumber:"",claimCode:"",vehicleId:""}),[ticket,setTicket]=useState({subject:"",description:""}),[qr,setQr]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{const r=await fetch("/api/me",{cache:"no-store"});if(r.status===401)return window.location.assign("/login");const j=await r.json();if(!r.ok)setError(j.error);else setData(j);},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!data)return;for(const v of data.vehicles){const code=activeCode(v);if(code&&!qr[code.id])void QRCode.toDataURL(`${window.location.origin}/t/${code.public_token}`,{width:260,margin:2,color:{dark:"#071d2b",light:"#ffffff"}}).then(img=>setQr(q=>({...q,[code.id]:img})));}},[data,qr]);
  const activeCodes=useMemo(()=>data?.vehicles.map(activeCode).filter(Boolean) as Code[]|undefined,[data]);
  async function post(url:string,payload:unknown){setBusy(true);setError("");setNotice("");const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error);return false;}await load();return true;}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.assign("/login");}
  async function createVehicle(){if(await post("/api/vehicles",{...form,year:form.year?Number(form.year):undefined})){setForm({manufacturer:"",model:"",color:"",year:""});setNotice("تمت إضافة السيارة");}}
  async function claimCard(){if(await post("/api/codes/claim",claim)){setClaim({serialNumber:"",claimCode:"",vehicleId:""});setNotice("تم تفعيل بطاقة دورني وربطها بالسيارة");}}
  async function createTicket(){if(await post("/api/support",{category:"GENERAL",...ticket})){setTicket({subject:"",description:""});setNotice("تم فتح تذكرة دعم، نتابعها معاك من داخل الحساب");}}
  if(!data)return <main className="loading-screen" dir="rtl"><RefreshCw className="spin"/><p>جاري تحميل حسابك...</p></main>;
  return <main className="real-owner-page" dir="rtl"><WebMcpTools onChanged={load}/><header className="owner-real-header"><button className="menu-button" onClick={()=>setMenu(true)} aria-label="فتح القائمة"><Menu/></button><DorniBrand/><div><span className="phone-chip">{data.user.phone}</span><button onClick={logout} aria-label="تسجيل الخروج"><LogOut/></button></div></header>
  {menu&&<div className="owner-drawer"><button className="drawer-backdrop" onClick={()=>setMenu(false)} aria-label="إغلاق"/><aside><button className="drawer-close" onClick={()=>setMenu(false)}><X/></button><DorniBrand/><nav><button onClick={()=>{setPanel("support");setMenu(false)}}><Headphones/> الدعم الفني</button><button onClick={()=>{setPanel("guide");setMenu(false)}}><BookOpen/> كيفية استخدام دورني</button><button onClick={()=>{setPanel("privacy");setMenu(false)}}><ShieldCheck/> الشروط والخصوصية</button><button onClick={()=>{setPanel("settings");setMenu(false)}}><Settings/> الإعدادات</button><button onClick={logout}><LogOut/> تسجيل الخروج</button></nav></aside></div>}
  <section className="owner-real-content"><div className="owner-real-lead"><div><p className="eyebrow">حساب صاحب السيارة</p><h1>{panel?panel==="support"?"الدعم الفني":panel==="guide"?"كيفية استخدام دورني":panel==="privacy"?"الشروط والخصوصية":"الإعدادات":tab==="vehicles"?"سياراتي وبطاقاتي":tab==="alerts"?"التنبيهات الواردة":"بياناتي"}</h1></div><Badge className="soft-badge"><span className="live-dot"/> حساب فعّال</Badge></div>{error&&<div className="form-error block-error" role="alert">{error}</div>}{notice&&<div className="success-banner"><Check/> {notice}</div>}
  {panel?<section className="work-card settings-panel"><Button variant="ghost" onClick={()=>setPanel(null)}>رجوع للحساب</Button>{panel==="support"&&<><h2>افتح تذكرة دعم</h2><p>التذكرة تُحفظ ويتابعها فريق دورني، مش صفحة ميتة.</p><Input placeholder="عنوان المشكلة" value={ticket.subject} onChange={e=>setTicket({...ticket,subject:e.target.value})}/><Textarea placeholder="اشرح المشكلة" value={ticket.description} onChange={e=>setTicket({...ticket,description:e.target.value})}/><Button onClick={createTicket} disabled={busy||!ticket.subject||!ticket.description}>إرسال للدعم</Button></>}{panel==="guide"&&<div className="guide-steps"><h2>من البطاقة إلى التنبيه</h2><ol><li>أضف سيارتك.</li><li>اكشط منطقة رمز المطالبة في بطاقة دورني.</li><li>أدخل الرقم التسلسلي ورمز المطالبة لتفعيل البطاقة.</li><li>ثبّت البطاقة في مكان واضح.</li><li>أي شخص يمسح QR يختار سبباً جاهزاً، من غير ما يشوف رقمك.</li></ol></div>}{panel==="privacy"&&<><h2>خصوصيتك هي الأساس</h2><p>الماسح يرى نوع السيارة ولونها فقط. لا نعرض اسمك أو رقم هاتفك أو واتساب أو أي وسيلة تواصل مباشرة. روابط متابعة البلاغ مؤقتة وغير قابلة للتخمين.</p></>}{panel==="settings"&&<><h2>قنوات التنبيه</h2><p>القناة الأساسية: <b>{data.preferences.primary_channel}</b></p><p>إدارة واتساب وSMS والإشعارات الفورية ستظهر هنا بعد تفعيل كل مزوّد والتحقق من الوجهة.</p></>}</section>:<>
  <nav className="real-tabs"><button className={tab==="account"?"active":""} onClick={()=>setTab("account")}><CircleUserRound/> بياناتي</button><button className={tab==="alerts"?"active":""} onClick={()=>setTab("alerts")}><Bell/> التنبيهات <i>{data.reports.filter(r=>r.status==="ACTIVE").length}</i></button><button className={tab==="vehicles"?"active":""} onClick={()=>setTab("vehicles")}><CarFront/> سياراتي</button></nav>
  {tab==="vehicles"&&<div className="owner-work-grid"><div><article className="work-card"><div className="card-heading"><div><h2>إضافة سيارة</h2><p>المعلومات العامة فقط، لوحة السيارة غير مطلوبة</p></div><Plus/></div><div className="vehicle-form"><Input placeholder="الشركة" value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/><Input placeholder="الموديل" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/><Input placeholder="اللون" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/><Input placeholder="السنة (اختياري)" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><Button onClick={createVehicle} disabled={busy||!form.manufacturer||!form.model||!form.color}><Plus/> حفظ السيارة</Button></div></article>
  <article className="work-card claim-card"><div className="card-heading"><div><h2>تفعيل بطاقة دورني</h2><p>الرمز تحت طبقة الكشط يُستخدم مرة واحدة</p></div><QrCode/></div><Input dir="ltr" placeholder="DRN-LY-000001" value={claim.serialNumber} onChange={e=>setClaim({...claim,serialNumber:e.target.value})}/><Input dir="ltr" placeholder="رمز المطالبة السري" value={claim.claimCode} onChange={e=>setClaim({...claim,claimCode:e.target.value})}/><select value={claim.vehicleId} onChange={e=>setClaim({...claim,vehicleId:e.target.value})}><option value="">اختر السيارة</option>{data.vehicles.map(v=><option value={v.id} key={v.id}>{v.manufacturer} {v.model} — {v.color}</option>)}</select><Button onClick={claimCard} disabled={busy||!claim.serialNumber||!claim.claimCode||!claim.vehicleId}>تفعيل وربط البطاقة</Button></article>
  <div className="vehicle-list">{data.vehicles.map(v=>{const code=activeCode(v);return <article className="vehicle-real-card" key={v.id}><span><CarFront/></span><div><h3>{v.manufacturer} {v.model}</h3><p>{v.color}{v.year?` • ${v.year}`:""}</p>{code&&<small dir="ltr">{code.serial_number}</small>}</div>{code?<Badge className="soft-badge"><Check/> مفعّل</Badge>:<Badge variant="outline">بانتظار بطاقة</Badge>}</article>})}</div></div>
  <aside className="qr-live-card"><div className="card-heading"><div><h2>بطاقاتك الفعّالة</h2><p>كل QR صادر حصراً من محرّك Dorni</p></div><ShieldCheck/></div>{activeCodes?.length?activeCodes.map(code=><div className="active-qr" key={code.id}>{qr[code.id]&&<img src={qr[code.id]} alt="رمز QR الخاص بالسيارة"/>}<b dir="ltr">{code.serial_number}</b><a href={`/t/${code.public_token}`} target="_blank">فتح صفحة المسح</a><Button variant="outline" onClick={()=>navigator.clipboard.writeText(`${location.origin}/t/${code.public_token}`)}><Copy/> نسخ الرابط</Button></div>):<div className="empty-code"><QrCode/><p>أضف سيارة ثم فعّل بطاقة دورني أصلية.</p></div>}</aside></div>}
  {tab==="alerts"&&<div className="reports-real-list">{data.reports.length===0?<div className="empty-state"><Bell/><h2>ما فيش تنبيهات توا</h2><p>أي بلاغ من بطاقة فعّالة بيظهر هنا مع سجل حالته.</p></div>:data.reports.map(r=><article key={r.id}><div><Badge className={r.status==="ACTIVE"?"urgent-badge":"soft-badge"}>{r.status==="ACTIVE"?"يحتاج رد":r.status==="RESOLVED"?"تم الحل":"تم الرد"}</Badge><h3>{reportLabel[r.report_type_code]??r.report_type_code}</h3><p>{r.vehicles?.manufacturer} {r.vehicles?.model} • {new Date(r.created_at).toLocaleString("ar-LY")}{r.duplicate_count>1?` • ${r.duplicate_count} بلاغات مماثلة`:""}</p></div><div className="report-buttons"><Button onClick={()=>post(`/api/reports/${r.id}/respond`,{response:"ON_MY_WAY"})}>جاي للسيارة</Button><Button variant="outline" onClick={()=>post(`/api/reports/${r.id}/respond`,{response:"RESOLVED"})}>تم حل الموضوع</Button><Button variant="ghost" onClick={()=>post(`/api/reports/${r.id}/respond`,{response:"CANNOT_REACH_NOW"})}>مش قادر نوصل توا</Button></div></article>)}</div>}
  {tab==="account"&&<div className="account-grid"><article className="account-real-card"><span><CircleUserRound/></span><div><p>رقم الهاتف الموثّق</p><h2 dir="ltr">{data.user.phone}</h2><small>حالة الحساب: {data.profile.account_status}</small></div></article><article className="account-real-card"><span><CarFront/></span><div><p>ملخص الحساب</p><h2>{data.vehicles.length} سيارات • {activeCodes?.length??0} بطاقات فعّالة</h2><small>{data.reports.length} تنبيهات محفوظة في السجل</small></div></article></div>}</>}
  </section></main>;
}
