"use client";
/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-location-assign-relative-destination */
import {useCallback,useEffect,useMemo,useState} from "react";
import {Activity,Boxes,Building2,Check,ClipboardCheck,Copy,FileDown,History,LifeBuoy,LogOut,RefreshCw,Search,ShieldCheck,Siren,Users,X} from "lucide-react";
import {DorniBrand} from "@/components/dorni-brand";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";
import {ApiError,errorMessage,requestJson} from "@/lib/client-api";

type Organization={id:string;name:string;type:string;status:"PENDING"|"ACTIVE"|"SUSPENDED"|"REJECTED";trusted_generation:boolean;registration_number:string|null;generation_limit_per_day:number;reviewed_at:string|null;review_note:string|null;created_at:string;admin_user_id:string|null;admin_name:string|null;admin_email:string|null};
type BatchRequest={id:string;quantity:number;product_type:string;status:string;notes:string|null;review_note:string|null;created_at:string;reviewed_at:string|null;organization_id:string;organization_name:string};
type Overview={role:string;metrics:Record<string,number>;organizations:Organization[];batchRequests:BatchRequest[];recentBatches:{id:string;batch_code:string;quantity:number;generated_count:number;generation_status:string;organization_id:string|null;created_at:string}[];recentReports:{id:string;report_type_code:string;status:string;duplicate_count:number;created_at:string}[];supportTickets:{id:string;subject:string;category:string;status:string;created_at:string}[];auditLogs:{id:string;actor_kind:string;action:string;entity_type:string;entity_id:string|null;safe_metadata:Record<string,unknown>;created_at:string}[]};
type PartnerDraft={trustedGeneration:boolean;generationLimit:number;note:string};
type View="overview"|"partners"|"requests"|"operations"|"audit";

const typeLabel:Record<string,string>={INSURANCE:"تأمين",CORPORATE:"شركة",DISTRIBUTOR:"موزع",OTHER:"أخرى"};
const statusLabel:Record<string,string>={PENDING:"قيد المراجعة",ACTIVE:"فعّال",SUSPENDED:"موقوف",REJECTED:"مرفوض",APPROVED:"موافق عليه",FULFILLED:"تم التنفيذ",OPEN:"مفتوحة",IN_PROGRESS:"قيد المعالجة",RESOLVED:"محلولة",CLOSED:"مغلقة",FAILED:"فشل"};
const actionLabel:Record<string,string>={PARTNER_APPLICATION_SUBMITTED:"تسجيل شركة جديدة",PARTNER_STATUS_CHANGED:"تعديل حالة شركة",PARTNER_CREATED:"إنشاء شركة بواسطة الإدارة",BATCH_REQUEST_REVIEWED:"مراجعة طلب أكواد",BATCH_GENERATED:"إنتاج دفعة أكواد",ADMIN_BOOTSTRAPPED:"تفعيل الإدارة"};

export default function AdminPage(){
  const [data,setData]=useState<Overview|null>(null),[view,setView]=useState<View>("overview"),[query,setQuery]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[inviteUrl,setInviteUrl]=useState(""),[busy,setBusy]=useState(false);
  const [batch,setBatch]=useState({organizationId:"",quantity:"100",productType:"STANDARD_CARD"});
  const [partner,setPartner]=useState({name:"",type:"CORPORATE",adminEmail:"",trustedGeneration:false});
  const [drafts,setDrafts]=useState<Record<string,PartnerDraft>>({});
  const load=useCallback(async()=>{try{const next=await requestJson<Overview>("/api/admin/overview");setData(next);setError("");setDrafts(current=>Object.fromEntries(next.organizations.map(org=>[org.id,current[org.id]??{trustedGeneration:org.trusted_generation,generationLimit:org.generation_limit_per_day,note:org.review_note??""}])));}catch(e){if(e instanceof ApiError&&e.status===401){location.assign("/login");return;}setError(errorMessage(e));}},[]);
  useEffect(()=>{void load();},[load]);
  const filteredOrganizations=useMemo(()=>{const term=query.trim().toLowerCase();if(!term)return data?.organizations??[];return (data?.organizations??[]).filter(org=>[org.name,org.admin_name,org.admin_email,org.registration_number].some(value=>value?.toLowerCase().includes(term)));},[data,query]);
  async function post<T>(url:string,payload:unknown){if(busy)return null;setBusy(true);setError("");setNotice("");try{const result=await requestJson<T>(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});await load();return result;}catch(e){setError(errorMessage(e));return null;}finally{setBusy(false);}}
  async function createBatch(){const result=await post<{batch:{batchCode:string}}>("/api/admin/batches",{...batch,organizationId:batch.organizationId||null,quantity:Number(batch.quantity)});if(result)setNotice(`تم إنشاء الدفعة ${result.batch.batchCode} وحفظ ملف الإنتاج الآمن.`);}
  async function createPartner(){const result=await post<{invitation?:{url?:string}|null}>("/api/admin/partners",partner);if(result){setInviteUrl(result.invitation?.url??"");setNotice(result.invitation?"تم إنشاء الشركة. رابط الدعوة جاهز لمديرها.":"تم إنشاء الشركة وربط مديرها الموجود.");setPartner({name:"",type:"CORPORATE",adminEmail:"",trustedGeneration:false});}}
  async function reviewPartner(org:Organization,status:"ACTIVE"|"SUSPENDED"|"REJECTED"){const draft=drafts[org.id]??{trustedGeneration:false,generationLimit:100,note:""};const result=await post(`/api/admin/partners/${org.id}`,{status,trustedGeneration:draft.trustedGeneration,generationLimit:draft.generationLimit,note:draft.note});if(result)setNotice(status==="ACTIVE"?`تم اعتماد ${org.name}.`:`تم تحديث حالة ${org.name}.`);}
  async function reviewRequest(item:BatchRequest,status:"APPROVED"|"REJECTED"){const result=await post(`/api/admin/batch-requests/${item.id}`,{status,note:""});if(result)setNotice(status==="APPROVED"?`تمت الموافقة على طلب ${item.organization_name}.`:"تم رفض الطلب وتسجيل القرار.");}
  async function logout(){try{await requestJson("/api/auth/logout",{method:"POST"});location.assign("/login");}catch(e){setError(errorMessage(e));}}
  function updateDraft(id:string,patch:Partial<PartnerDraft>){setDrafts(current=>({...current,[id]:{...(current[id]??{trustedGeneration:false,generationLimit:100,note:""}),...patch}}));}
  if(!data&&!error)return <main className="loading-screen" dir="rtl"><RefreshCw className="spin"/> جاري تحميل مركز الإدارة</main>;
  if(!data)return <main className="loading-screen" dir="rtl"><ShieldCheck/><h1>لوحة الإدارة محمية</h1><p>{error==="FORBIDDEN"?"هذا الحساب ليس حساب مدير دورني.":error}</p><a href="/login">الرجوع لتسجيل الدخول</a></main>;
  const pendingPartners=data.organizations.filter(org=>org.status==="PENDING"),pendingRequests=data.batchRequests.filter(item=>item.status==="PENDING");
  return <main className="admin-control" dir="rtl"><aside className="admin-control-sidebar"><DorniBrand href="/admin"/><div className="admin-role"><ShieldCheck/><div><b>مدير دورني</b><small>{data.role}</small></div></div><nav aria-label="أقسام الإدارة"><button className={view==="overview"?"active":""} onClick={()=>setView("overview")}><Activity/> نظرة عامة</button><button className={view==="partners"?"active":""} onClick={()=>setView("partners")}><Building2/> الشركات والموزعون {pendingPartners.length>0&&<i>{pendingPartners.length}</i>}</button><button className={view==="requests"?"active":""} onClick={()=>setView("requests")}><ClipboardCheck/> طلبات الأكواد {pendingRequests.length>0&&<i>{pendingRequests.length}</i>}</button><button className={view==="operations"?"active":""} onClick={()=>setView("operations")}><Boxes/> الإنتاج والعمليات</button><button className={view==="audit"?"active":""} onClick={()=>setView("audit")}><History/> سجل الإدارة</button></nav><button className="admin-logout" onClick={logout}><LogOut/> تسجيل الخروج</button></aside><section className="admin-control-main"><header><div><p>لوحة تحكم مركزية</p><h1>{view==="overview"?"نظرة عامة":view==="partners"?"إدارة الشركات والموزعين":view==="requests"?"طلبات إنتاج الأكواد":view==="operations"?"الإنتاج والمتابعة":"سجل القرارات"}</h1></div><div className="admin-live"><span/> متصل ببيانات دورني</div></header><div className="admin-control-content">{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success-banner"><Check/> {notice}</p>}
  {view==="overview"&&<><section className="admin-summary-grid"><article><span><Users/></span><p>إجمالي المستخدمين</p><b>{data.metrics.users??0}</b></article><article><span><Building2/></span><p>طلبات شركات تنتظر</p><b>{data.metrics.pendingPartners??0}</b></article><article><span><Siren/></span><p>بلاغات تحتاج متابعة</p><b>{data.metrics.activeReports??0}</b></article><article><span><LifeBuoy/></span><p>تذاكر دعم مفتوحة</p><b>{data.metrics.support??0}</b></article><article><span><Boxes/></span><p>إجمالي الأكواد</p><b>{data.metrics.codes??0}</b></article><article><span><X/></span><p>إشعارات فاشلة</p><b>{data.metrics.failedNotifications??0}</b></article></section>{pendingPartners.length>0&&<section className="admin-priority"><div><ShieldCheck/><div><b>عندك {pendingPartners.length} طلب شركة ينتظر القرار</b><p>راجع الهوية والسجل التجاري قبل منح صلاحية إنتاج الأكواد.</p></div></div><Button onClick={()=>setView("partners")}>فتح المراجعات</Button></section>}<div className="admin-dashboard-grid"><article className="work-card"><h2>آخر البلاغات</h2>{data.recentReports.slice(0,6).map(report=><div className="list-row" key={report.id}><div><b>{report.report_type_code}</b><p>{new Date(report.created_at).toLocaleString("ar-LY")}</p></div><Badge variant="outline">{statusLabel[report.status]??report.status}</Badge></div>)}{!data.recentReports.length&&<p>لا توجد بلاغات.</p>}</article><article className="work-card"><h2>آخر تذاكر الدعم</h2>{data.supportTickets.slice(0,6).map(ticket=><div className="list-row" key={ticket.id}><div><b>{ticket.subject}</b><p>{ticket.category}</p></div><Badge variant="outline">{statusLabel[ticket.status]??ticket.status}</Badge></div>)}{!data.supportTickets.length&&<p>لا توجد تذاكر دعم.</p>}</article></div></>}
  {view==="partners"&&<><div className="admin-toolbar"><label><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الشركة أو البريد أو السجل"/></label><span>{filteredOrganizations.length} شركة</span></div><section className="partner-review-list">{filteredOrganizations.map(org=>{const draft=drafts[org.id]??{trustedGeneration:org.trusted_generation,generationLimit:org.generation_limit_per_day,note:org.review_note??""};return <article className={`partner-review-card status-${org.status.toLowerCase()}`} key={org.id}><div className="partner-review-head"><div><span className="partner-avatar"><Building2/></span><div><h2>{org.name}</h2><p>{typeLabel[org.type]??org.type} • سُجل {new Date(org.created_at).toLocaleDateString("ar-LY")}</p></div></div><Badge>{statusLabel[org.status]??org.status}</Badge></div><dl><div><dt>مدير الحساب</dt><dd>{org.admin_name||"غير محدد"}</dd></div><div><dt>البريد</dt><dd dir="ltr">{org.admin_email||"—"}</dd></div><div><dt>السجل التجاري</dt><dd dir="ltr">{org.registration_number||"غير مرفق"}</dd></div></dl><div className="partner-controls"><label><span>حد الأكواد اليومي</span><Input type="number" min="1" max="100000" value={draft.generationLimit} onChange={e=>updateDraft(org.id,{generationLimit:Number(e.target.value)})}/></label><label className="check-row"><input type="checkbox" checked={draft.trustedGeneration} onChange={e=>updateDraft(org.id,{trustedGeneration:e.target.checked})}/><span>السماح بالإنتاج المباشر بدون طلب يدوي</span></label><label className="wide"><span>ملاحظة القرار تظهر للشركة</span><Input value={draft.note} onChange={e=>updateDraft(org.id,{note:e.target.value})} placeholder="مثال: يرجى استكمال بيانات السجل"/></label></div><div className="partner-review-actions"><Button disabled={busy} onClick={()=>reviewPartner(org,"ACTIVE")}><Check/> اعتماد وتفعيل</Button><Button variant="outline" disabled={busy} onClick={()=>reviewPartner(org,"SUSPENDED")}>إيقاف مؤقت</Button><Button variant="ghost" disabled={busy} onClick={()=>reviewPartner(org,"REJECTED")}><X/> رفض</Button></div></article>})}{!filteredOrganizations.length&&<div className="empty-state"><Building2/><h2>لا توجد نتائج</h2></div>}</section></>}
  {view==="requests"&&<section className="admin-request-list">{data.batchRequests.map(item=><article key={item.id}><div><span><Boxes/></span><div><h2>{item.organization_name}</h2><p>{item.quantity} كود • {item.product_type} • {new Date(item.created_at).toLocaleString("ar-LY")}</p>{item.notes&&<small>{item.notes}</small>}</div></div><Badge variant="outline">{statusLabel[item.status]??item.status}</Badge>{item.status==="PENDING"&&<div className="request-actions"><Button disabled={busy} onClick={()=>reviewRequest(item,"APPROVED")}><Check/> موافقة</Button><Button variant="ghost" disabled={busy} onClick={()=>reviewRequest(item,"REJECTED")}><X/> رفض</Button></div>}</article>)}{!data.batchRequests.length&&<div className="empty-state"><ClipboardCheck/><h2>لا توجد طلبات أكواد</h2></div>}</section>}
  {view==="operations"&&<><div className="admin-dashboard-grid"><article className="work-card admin-form"><h2>إنشاء شركة بدعوة إدارية</h2><Input placeholder="اسم الشركة" value={partner.name} onChange={e=>setPartner({...partner,name:e.target.value})}/><select value={partner.type} onChange={e=>setPartner({...partner,type:e.target.value})}><option value="CORPORATE">شركة</option><option value="DISTRIBUTOR">موزع</option><option value="INSURANCE">تأمين</option><option value="OTHER">أخرى</option></select><Input dir="ltr" type="email" placeholder="بريد مدير الشركة" value={partner.adminEmail} onChange={e=>setPartner({...partner,adminEmail:e.target.value})}/><label className="check-row"><input type="checkbox" checked={partner.trustedGeneration} onChange={e=>setPartner({...partner,trustedGeneration:e.target.checked})}/><span>السماح بالإنتاج المباشر</span></label><Button onClick={createPartner} disabled={busy||!partner.name||!partner.adminEmail}><Building2/> إنشاء وإصدار دعوة</Button>{inviteUrl&&<div className="invite-result"><Input dir="ltr" readOnly value={inviteUrl}/><Button variant="outline" onClick={()=>navigator.clipboard.writeText(inviteUrl)}><Copy/> نسخ</Button></div>}</article><article className="work-card admin-form"><h2>إنتاج دفعة أكواد</h2><select value={batch.organizationId} onChange={e=>setBatch({...batch,organizationId:e.target.value})}><option value="">دفعة مباشرة لدورني</option>{data.organizations.filter(org=>org.status==="ACTIVE").map(org=><option value={org.id} key={org.id}>{org.name}</option>)}</select><Input type="number" min="1" max="1000" value={batch.quantity} onChange={e=>setBatch({...batch,quantity:e.target.value})}/><Button onClick={createBatch} disabled={busy||Number(batch.quantity)<1||Number(batch.quantity)>1000}><Boxes/> إنشاء الدفعة</Button><small><FileDown/> ملف التفعيل السري يُحفظ مؤقتًا ولا يظهر للعامة.</small></article></div><article className="work-card"><h2>آخر دفعات الإنتاج</h2>{data.recentBatches.map(item=><div className="list-row" key={item.id}><div><b dir="ltr">{item.batch_code}</b><p>{item.generated_count}/{item.quantity} كود • {new Date(item.created_at).toLocaleDateString("ar-LY")}</p></div><Badge variant="outline">{item.generation_status}</Badge></div>)}</article></>}
  {view==="audit"&&<section className="audit-list">{data.auditLogs.map(log=><article key={log.id}><span><History/></span><div><b>{actionLabel[log.action]??log.action}</b><p>{log.entity_type} • {new Date(log.created_at).toLocaleString("ar-LY")}</p></div><Badge variant="outline">{log.actor_kind}</Badge></article>)}{!data.auditLogs.length&&<div className="empty-state"><History/><h2>لا توجد أحداث إدارية</h2></div>}</section>}
  </div></section></main>;
}

