import {createHash} from "node:crypto";
import {z} from "zod";
import {body,json,requireUser,UnauthorizedError} from "@/lib/server/http";
import {randomToken} from "@/lib/server/security";
import {validPushOrigin} from "@/lib/server/push-origin";
const invite=z.object({action:z.literal("invite"),organizationId:z.string().uuid(),email:z.string().email(),roleId:z.string().uuid()});
const status=z.object({action:z.literal("status"),organizationId:z.string().uuid(),membershipId:z.string().uuid(),status:z.enum(["ACTIVE","SUSPENDED"])});
const revoke=z.object({action:z.literal("revoke-invitation"),organizationId:z.string().uuid(),invitationId:z.string().uuid()});
const role=z.object({action:z.literal("role"),organizationId:z.string().uuid(),membershipId:z.string().uuid(),roleId:z.string().uuid()});
export async function POST(request:Request){try{if(!validPushOrigin(request,process.env.NEXT_PUBLIC_APP_URL))return json({error:"عنوان الطلب غير مسموح"},403);const value=z.discriminatedUnion("action",[invite,status,revoke,role]).parse(await body(request));const {supabase}=await requireUser();if(value.action==="status"){const {data,error}=await supabase.rpc("org_set_member_status",{p_organization_id:value.organizationId,p_membership_id:value.membershipId,p_status:value.status});if(error)return json({error:"تعذر تحديث حالة الموظف أو لا يمكن إيقاف آخر مدير"},403);return json({membership:data});}if(value.action==="role"){const {data,error}=await supabase.rpc("org_set_member_role",{p_organization_id:value.organizationId,p_membership_id:value.membershipId,p_role_id:value.roleId});if(error)return json({error:"تعذر تغيير الدور أو يجب الإبقاء على مدير واحد على الأقل"},403);return json({membership:data});}if(value.action==="revoke-invitation"){const {data,error}=await supabase.rpc("org_revoke_invitation",{p_organization_id:value.organizationId,p_invitation_id:value.invitationId});if(error)return json({error:"تعذر إلغاء الدعوة أو لم تعد نشطة"},403);return json({invitation:data});}const token=randomToken(32);const tokenHash=createHash("sha256").update(token).digest("hex");const {data,error}=await supabase.rpc("org_invite_member",{p_organization_id:value.organizationId,p_email:value.email.toLowerCase(),p_role_id:value.roleId,p_token_hash:tokenHash});if(error)return json({error:"تعذر إنشاء الدعوة أو لا تملك الصلاحية"},403);return json({invitation:{...data,url:`${process.env.NEXT_PUBLIC_APP_URL??new URL(request.url).origin}/login?invite=${encodeURIComponent(token)}`}},201);}catch(error){return json({error:error instanceof UnauthorizedError?"UNAUTHORIZED":"بيانات الطلب غير صالحة"},error instanceof UnauthorizedError?401:400);}}

