"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useCallback,useEffect,useState} from "react";
import {Building2,Check,Copy,History,RefreshCw,Send,ShieldCheck,UserRoundPlus,Users} from "lucide-react";
import {requestJson,errorMessage} from "@/lib/client-api";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";

type Capabilities={actions:boolean;members:boolean;invite:boolean;roles:boolean;audit:boolean;reports:boolean};
type Action={id:string;referenceNumber:string;reasonCode:string;status:string;ownerResponse:string|null;createdAt:string;acknowledgedAt:string|null;completedAt:string|null};
type Role={id:string;code:string;name:string;systemRole:boolean;permissions:string[]};
type Overview={organization:{id:string;name:string;status:string;institutionalEnabled:boolean;institutionalStatus:string};capabilities:Capabilities;metrics:{total?:number;sent?:number;delivered?:number;acknowledged?:number;completed?:number;unacknowledged?:number};actions:Action[];members:{id:string;name:string|null;email:string|null;status:string;roleId:string|null;roleName:string|null;actionCount:number;lastActivity:string|null}[];roles:Role[];entitlements:string[];invitations:{id:string;email:string;roleId:string;roleName:string|null;createdAt:string;expiresAt:string;status:string}[];audit:{id:string;action:string;entityType:string;entityId:string;createdAt:string}[]};
const permissionLabels:Record<string,string>={ORG_MEMBER_VIEW:"عرض الموظفين",ORG_MEMBER_INVITE:"دعوة موظف",ORG_MEMBER_SUSPEND:"إيقاف موظف",ORG_ROLE_ASSIGN:"إدارة الأدوار",ORG_AUDIT_VIEW:"عرض التدقيق",ORG_REPORT_VIEW:"عرض التقارير",VEHICLE_MOVE_REQUEST:"طلب تحريك مركبة"};
const reasonLabels:Record<string,string>={BLOCKING_ACCESS:"تعيق الوصول أو الخروج",OBSTRUCTING_TRAFFIC:"تعرقل حركة المرور",SAFETY_REASON:"سبب متعلق بالسلامة",OTHER:"سبب آخر"};
const statusLabels:Record<string,string>={SENT:"أُرسل",DELIVERED:"وصل",ACKNOWLEDGED:"اطّلع المالك",COMPLETED:"مغلق",FAILED:"فشل",CANCELLED:"ملغي",EXPIRED:"منتهي",PENDING:"بانتظار القبول",CLAIMED:"مقبولة",REVOKED:"ملغاة"};

export function InstitutionalWorkspace({organizationId}:{organizationId:string}){
  const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[inviteUrl,setInviteUrl]=useState("");
  const [invite,setInvite]=useState({email:"",roleId:""});
  const [role,setRole]=useState({id:null as string|null,code:"FIELD_AGENT",name:"موظف ميداني",permissions:["VEHICLE_MOVE_REQUEST"] as string[]});
  const load=useCallback(async(silent=false)=>{try{setData(await requestJson<Overview>(`/api/institutional/overview?organizationId=${encodeURIComponent(organizationId)}`));if(!silent)setError("");}catch(e){if(!silent)setError(errorMessage(e));}},[organizationId]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),15000);return()=>window.clearInterval(timer);},[load]);
  async function post(url:string,payload:unknown){setBusy(true);setError("");setNotice("");try{await requestJson(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});await load();return true;}catch(e){setError(errorMessage(e));return false;}finally{setBusy(false);}}
  if(!data&&!error)return <article className="work-card institutional-panel"><RefreshCw className="spin"/> جاري تحميل مساحة المؤسسة…</article>;
  if(!data)return <article className="work-card institutional-panel"><ShieldCheck/><h2>الخدمات المؤسسية غير متاحة</h2><p>{error}</p></article>;
  if(!data.organization.institutionalEnabled||data.organization.institutionalStatus!=="VERIFIED")return null;
  const assignable=data.roles.filter(item=>item.code!=="PARTNER_ADMIN");
  return <section className="institutional-workspace" aria-label="مساحة المؤسسة الموثقة">
    <div className="institutional-title"><div><ShieldCheck/><span><b>مؤسسة موثقة عبر دورني</b><small>كل إجراء مربوط بالمؤسسة والموظف وتعيين رمز المركبة، ومسجل للتدقيق.</small></span></div><Badge>موثقة</Badge></div>
    {error&&<p className="form-error">{error}</p>}{notice&&<p className="success-banner"><Check/> {notice}</p>}
    {(data.capabilities.actions||data.capabilities.reports)&&<div className="metric-grid"><article><Send/><b>{data.metrics.total??0}</b><span>إجراءات</span></article><article><Check/><b>{data.metrics.acknowledged??0}</b><span>تم الاطلاع</span></article><article><Users/><b>{data.metrics.completed??0}</b><span>مغلقة</span></article></div>}
    {(data.capabilities.roles||data.capabilities.invite)&&<div className="portal-grid">
      {data.capabilities.roles&&<article className="work-card admin-form"><h2>{role.id?"تعديل الدور":"إنشاء دور مؤسسي"}</h2><Input value={role.name} onChange={e=>setRole({...role,name:e.target.value})}/><Input dir="ltr" value={role.code} disabled={Boolean(role.id)} onChange={e=>setRole({...role,code:e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,"")})}/><div className="permission-list">{data.entitlements.map(permission=><label key={permission}><input type="checkbox" checked={role.permissions.includes(permission)} onChange={e=>setRole({...role,permissions:e.target.checked?[...role.permissions,permission]:role.permissions.filter(item=>item!==permission)})}/>{permissionLabels[permission]??permission}</label>)}</div><div className="member-actions"><Button disabled={busy||!role.name||!role.code} onClick={async()=>{if(await post("/api/institutional/roles",{organizationId,roleId:role.id,code:role.code,name:role.name,permissions:role.permissions})){setNotice(role.id?"تم تحديث الدور والصلاحيات.":"تم إنشاء الدور ضمن تخويل المؤسسة.");setRole({id:null,code:"FIELD_AGENT",name:"موظف ميداني",permissions:["VEHICLE_MOVE_REQUEST"]});}}}>حفظ الدور</Button>{role.id&&<Button variant="outline" onClick={()=>setRole({id:null,code:"FIELD_AGENT",name:"موظف ميداني",permissions:["VEHICLE_MOVE_REQUEST"]})}>إلغاء</Button>}</div>{data.roles.filter(item=>!item.systemRole).map(item=><div className="list-row" key={item.id}><div><b>{item.name}</b><p>{item.permissions.map(p=>permissionLabels[p]??p).join(" • ")}</p></div><Button variant="ghost" onClick={()=>setRole({id:item.id,code:item.code,name:item.name,permissions:item.permissions})}>تعديل</Button></div>)}</article>}
      {data.capabilities.invite&&<article className="work-card admin-form"><h2><UserRoundPlus/> دعوة موظف</h2><Input type="email" dir="ltr" placeholder="employee@example.com" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/><select value={invite.roleId} onChange={e=>setInvite({...invite,roleId:e.target.value})}><option value="">اختر الدور</option>{assignable.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><Button disabled={busy||!invite.email||!invite.roleId} onClick={async()=>{setBusy(true);setError("");setNotice("");setInviteUrl("");try{const response=await requestJson<{invitation:{url:string}}>("/api/institutional/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"invite",organizationId,...invite})});setInviteUrl(response.invitation.url);setInvite({email:"",roleId:""});setNotice("تم إنشاء دعوة آمنة، أحادية الاستخدام، وتنتهي تلقائيًا.");await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><UserRoundPlus/> إنشاء الدعوة</Button>{inviteUrl&&<div className="invite-link"><Input value={inviteUrl} dir="ltr" readOnly/><Button type="button" variant="outline" onClick={async()=>{await navigator.clipboard.writeText(inviteUrl);setNotice("تم نسخ رابط الدعوة.");}}><Copy/> نسخ الرابط</Button></div>}{data.invitations.map(item=><div className="list-row" key={item.id}><div><b dir="ltr">{item.email}</b><p>{item.roleName??"دور مؤسسي"} • {statusLabels[item.status]??item.status}</p></div>{item.status==="PENDING"&&<Button variant="ghost" disabled={busy} onClick={()=>void post("/api/institutional/members",{action:"revoke-invitation",organizationId,invitationId:item.id})}>إلغاء الدعوة</Button>}</div>)}</article>}
    </div>}
    {data.capabilities.members&&<article className="work-card"><h2>الموظفون</h2>{data.members.map(member=><div className="list-row" key={member.id}><div><b>{member.name||member.email||"موظف"}</b><p>{member.roleName??"دور غير محدد"} • {member.actionCount} إجراء {member.lastActivity?`• آخر نشاط ${new Date(member.lastActivity).toLocaleString("ar-LY")}`:""}</p></div><div className="member-actions">{data.capabilities.roles&&<select aria-label={`دور ${member.name||member.email||"الموظف"}`} value={member.roleId??""} disabled={busy} onChange={event=>void post("/api/institutional/members",{action:"role",organizationId,membershipId:member.id,roleId:event.target.value})}>{data.roles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}<Badge variant="outline">{member.status}</Badge><Button variant="ghost" disabled={busy} onClick={()=>void post("/api/institutional/members",{action:"status",organizationId,membershipId:member.id,status:member.status==="ACTIVE"?"SUSPENDED":"ACTIVE"})}>{member.status==="ACTIVE"?"إيقاف":"إعادة تفعيل"}</Button></div></div>)}</article>}
    {(data.capabilities.actions||data.capabilities.reports)&&<article className="work-card"><h2><Building2/> طلبات تحريك المركبات</h2>{data.actions.length?data.actions.map(action=><div className="list-row" key={action.id}><div><b dir="ltr">{action.referenceNumber}</b><p>{reasonLabels[action.reasonCode]??action.reasonCode} • {new Date(action.createdAt).toLocaleString("ar-LY")}{action.ownerResponse?` • رد المالك: ${action.ownerResponse==="WILL_MOVE"?"سأحرك المركبة":"تم الاطلاع"}`:""}</p></div><div className="member-actions"><Badge>{statusLabels[action.status]??action.status}</Badge>{data.capabilities.actions&&action.status==="ACKNOWLEDGED"&&<Button variant="ghost" disabled={busy} onClick={()=>void post(`/api/institutional/actions/${action.id}/complete`,{organizationId})}>إغلاق الإجراء</Button>}</div></div>):<p>لا توجد إجراءات في الفترة المحددة.</p>}</article>}
    {data.capabilities.audit&&<article className="work-card"><h2><History/> سجل التدقيق</h2>{data.audit.length?data.audit.map(item=><div className="list-row" key={item.id}><div><b>{item.action}</b><p>{item.entityType} • {new Date(item.createdAt).toLocaleString("ar-LY")}</p></div></div>):<p>لا توجد أحداث تدقيق في الفترة المحددة.</p>}</article>}
  </section>;
}

