"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useCallback,useEffect,useState} from "react";
import {Building2,Check,ShieldCheck} from "lucide-react";
import {requestJson,errorMessage} from "@/lib/client-api";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
type Action={id:string;referenceNumber:string;actionType:string;reasonCode:string;status:string;ownerResponse:string|null;createdAt:string;organization:{name:string;verified:boolean};vehicle:{manufacturer:string;model:string;color:string}};
const reasons:Record<string,string>={BLOCKING_ACCESS:"المركبة تعيق الوصول أو الخروج",OBSTRUCTING_TRAFFIC:"المركبة تعرقل حركة المرور",SAFETY_REASON:"سبب متعلق بالسلامة",OTHER:"سبب موثق آخر"};
export function OwnerInstitutionalAlerts(){const [actions,setActions]=useState<Action[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState("");const load=useCallback(async()=>{try{const data=await requestJson<{actions:Action[]}>("/api/institutional/owner");setActions(data.actions);setError("");}catch(e){setError(errorMessage(e));}},[]);useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(timer);},[load]);async function respond(id:string,response:"SEEN"|"WILL_MOVE"){setBusy(id);try{await requestJson(`/api/institutional/actions/${id}/respond`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({response})});await load();}catch(e){setError(errorMessage(e));}finally{setBusy("");}}const visible=actions.filter(a=>["SENT","DELIVERED","ACKNOWLEDGED"].includes(a.status));if(!visible.length&&!error)return null;return <section className="owner-institutional-alerts" aria-label="تنبيهات المؤسسات الموثقة">{error&&<p className="form-error">{error}</p>}{visible.map(a=><article key={a.id}><header><span><ShieldCheck/></span><div><p>تنبيه موثّق عبر دورني</p><h2><Building2/> {a.organization.name}</h2></div><Badge>{a.status==="ACKNOWLEDGED"?"تم الاطلاع":"يتطلب اطلاعك"}</Badge></header><p>{reasons[a.reasonCode]??"طلب تحريك المركبة"}</p><dl><div><dt>المركبة</dt><dd>{a.vehicle.manufacturer} {a.vehicle.model} — {a.vehicle.color}</dd></div><div><dt>رقم الإجراء</dt><dd dir="ltr">{a.referenceNumber}</dd></div><div><dt>وقت الإرسال</dt><dd>{new Date(a.createdAt).toLocaleString("ar-LY")}</dd></div></dl>{!a.ownerResponse?<div className="report-buttons"><Button disabled={busy===a.id} onClick={()=>void respond(a.id,"SEEN")}><Check/> تم الاطلاع</Button><Button variant="outline" disabled={busy===a.id} onClick={()=>void respond(a.id,"WILL_MOVE")}>سأحرك المركبة</Button></div>:<p className="success-banner"><Check/> {a.ownerResponse==="WILL_MOVE"?"تم تسجيل أنك ستحرك المركبة":"تم تسجيل اطلاعك"}</p>}</article>)}</section>}
