"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useLocale} from './locale-provider';
import './activation-journey.css';
import {serviceDuration,serviceLabels,type ServiceView} from '@/lib/service-view';
export {serviceLabels,type ServiceView} from '@/lib/service-view';
export function ServiceFacts({service:s}:{service:ServiceView}){
 const {t,dateLocale}=useLocale();const date=(v:string|null)=>v?new Date(v).toLocaleDateString(dateLocale,{year:'numeric',month:'long',day:'numeric'}):t('غير محدد');
 return <dl className="activation-summary"><div><dt>{t('المركبة')}</dt><dd>{s.vehicle.manufacturer} {s.vehicle.model} — {s.vehicle.color}</dd></div><div><dt>{t('بطاقتك')}</dt><dd className="activation-serial">{s.serial}</dd></div><div><dt>{t('نوع الخدمة')}</dt><dd>{t(s.plan)}{s.duration?` — ${t(serviceDuration(s.unit,s.duration))}`:''}</dd></div><div><dt>{t('حالة الخدمة')}</dt><dd>{t(serviceLabels[s.status]??'غير متاحة')}</dd></div><div><dt>{t('تاريخ البداية')}</dt><dd>{date(s.startsAt)}</dd></div><div><dt>{t('تاريخ الانتهاء')}</dt><dd>{s.expiresAt?date(s.expiresAt):t('دون تاريخ انتهاء محدد')}</dd></div></dl>;
}
export function ServiceDetail({initial}:{initial:ServiceView}){
 const {t}=useLocale();const router=useRouter();const [service,setService]=useState(initial),[choosing,setChoosing]=useState(false),[plans,setPlans]=useState<{id:string;name:string;duration:string}[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;const update=async()=>{if(document.visibilityState==='hidden')return;try{const r=await fetch('/api/service-requests',{cache:'no-store'});if(!r.ok)return;const j=await r.json();const found=j.data?.find((x:ServiceView)=>x.codeId===initial.codeId);if(alive&&found)setService(found);}catch{/* Keep last confirmed snapshot. */}};const timer=setInterval(()=>void update(),15000);window.addEventListener('focus',update);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',update);};},[initial.codeId]);
 async function choose(){setBusy(true);setError('');try{const r=await fetch('/api/services');if(r.status===401){router.push('/login');return;}const j=await r.json();if(!r.ok)throw Error();const active=j.data.plans.filter((p:{active:boolean})=>p.active);setPlans(active.map((p:{id:string;name:string})=>{const v=j.data.versions.filter((v:{plan_id:string})=>v.plan_id===p.id).sort((a:{version:number},b:{version:number})=>b.version-a.version)[0];return {id:v?.id,name:p.name,duration:serviceDuration(v?.duration_unit,v?.duration_value)};}).filter((p:{id?:string})=>p.id));setChoosing(true);}catch{setError(t('تعذر تحميل الخطط. حاول مجددًا.'));}finally{setBusy(false);}}
 async function request(){setBusy(true);setError('');try{const r=await fetch('/api/service-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'request',codeId:service.codeId,versionId:selected})});const j=await r.json();if(!r.ok)throw Error(j.error);setService(j.data);setChoosing(false);}catch(e){setError(e instanceof Error?e.message:t('تعذر إرسال الطلب'));}finally{setBusy(false);}}
 return <><section className="activation-box"><ServiceFacts service={service}/></section>{service.status==='SUSPENDED'&&<p className="activation-notice">{t('الخدمة معلقة إداريًا. التجديد لا يرفع التعليق. تواصل مع الدعم للمساعدة.')} <Link href="/app?tab=support">{t('الدعم الفني')}</Link></p>}{service.status==='PAUSED'&&<p className="activation-notice">{t('أوقفت الخدمة مؤقتًا. مدة الاشتراك مستمرة. يمكنك استئناف الخدمة من إعدادات بطاقتك.')}</p>}{service.pending?<section className="activation-notice" role="status"><strong>{t('طلب التجديد بانتظار التأكيد')}</strong><p>{t(service.pending.plan)} — {t('مدة الخدمة لم تتغير بعد. لا يتم التجديد إلا بعد اعتماد الطلب من الإدارة.')}</p></section>:service.renewable&&!choosing&&<button className="activation-primary" disabled={busy} onClick={()=>void choose()}>{t('تجديد الخدمة')}</button>}{choosing&&!service.pending&&<section className="activation-box"><h2>{t('اختر مدة التجديد')}</h2><p>{t('هذا طلب تجديد، وليس دفعًا أو تجديدًا مؤكدًا.')}</p>{plans.map(p=><label key={p.id} className="activation-choice"><input type="radio" name="renewal-plan" value={p.id} checked={selected===p.id} onChange={()=>setSelected(p.id)}/><span>{t(p.name)} — {t(p.duration)}</span></label>)}<button className="activation-primary" disabled={busy||!selected} onClick={()=>void request()}>{busy?t('جاري الإرسال…'):t('إرسال طلب التجديد')}</button><button className="activation-secondary" disabled={busy} onClick={()=>setChoosing(false)}>{t('رجوع')}</button></section>}{error&&<p className="activation-error" role="alert">{error}</p>}</>;
}
export function VehicleService({service}:{service:ServiceView}){const {t,dateLocale}=useLocale();return <div className="service-mini"><span className="service-status">{t(serviceLabels[service.status]??'غير متاحة')} · {t(service.plan)}</span><span>{service.expiresAt?t('تاريخ الانتهاء')+': '+new Date(service.expiresAt).toLocaleDateString(dateLocale):t('دون تاريخ انتهاء محدد')}</span>{service.pending&&<span>{t('طلب التجديد بانتظار التأكيد — مدة الخدمة لم تتغير بعد')}</span>}<Link href={`/app/service?code=${service.codeId}`}>{service.status==='EXPIRED'?t('تجديد الخدمة'):t('تفاصيل الخدمة والتجديد')}</Link></div>;}
