"use client";
import { FormEvent,Suspense,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import { ArrowLeft,Building2,Eye,EyeOff,KeyRound,Mail,ShieldCheck,UserRound } from "lucide-react";
import { DorniBrand } from "@/components/dorni-brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Portal="owner"|"partner";
type Mode="login"|"signup"|"forgot";
function LoginContent(){const router=useRouter(),params=useSearchParams();const invite=params.get("invite")??"",reason=params.get("error");const initialError=reason==="partner_invite"?"تعذر ربط دعوة الشركة. افتح رابط الدعوة من جديد.":reason==="email_link"?"رابط البريد غير صالح أو انتهت صلاحيته.":"";const [portal,setPortal]=useState<Portal>(invite?"partner":"owner"),[mode,setMode]=useState<Mode>(invite?"signup":"login"),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(initialError),[notice,setNotice]=useState("");
function changePortal(next:Portal){setPortal(next);setError("");setNotice("");if(next==="partner"&&!invite)setMode("login");}
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{if(mode==="forgot"){const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice("لو البريد مسجل، بيصلك رابط لتغيير كلمة المرور.");return;}const url=mode==="signup"?"/api/auth/signup":"/api/auth/login";const payload=mode==="signup"?{fullName,email,password,inviteToken:invite||undefined}:{email,password,portal};const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error);if(j.needsEmailConfirmation){setNotice("تم إنشاء الحساب. افتح رسالة التأكيد في بريدك وبعدها ادخل.");setMode("login");setPassword("");return;}router.replace(j.context?.destination??j.destination??(portal==="partner"?"/partner":"/app"));router.refresh();}catch(err){setError(err instanceof Error?err.message:"تعذر إكمال العملية");}finally{setBusy(false);}}
return <main className="auth-shell" dir="rtl"><header><DorniBrand/><span className="secure-chip"><ShieldCheck/> حسابات حقيقية ومشفرة</span></header><section className="auth-card account-auth-card"><div className="account-kind-tabs"><button className={portal==="owner"?"active":""} onClick={()=>changePortal("owner")}><UserRound/> صاحب سيارة</button><button className={portal==="partner"?"active":""} onClick={()=>changePortal("partner")}><Building2/> شركة / شريك</button></div><span className="auth-icon">{portal==="partner"?<Building2/>:mode==="forgot"?<KeyRound/>:<UserRound/>}</span><p className="eyebrow">{portal==="partner"?"بوابة الشركات":"حساب صاحب السيارة"}</p><h1>{mode==="signup"?invite?"فعّل حساب الشركة":"أنشئ حسابك":mode==="forgot"?"استرجع كلمة المرور":"تسجيل الدخول"}</h1><p>{invite?"الدعوة تربط حسابك بالشركة وصلاحياتها بشكل دائم.":portal==="partner"?"ادخل ببريد الشركة وكلمة المرور. إنشاء حساب شركة جديد يكون بدعوة آمنة من دورني.":"حسابك يحفظ السيارات والبطاقات والتنبيهات حتى بعد إغلاق التطبيق."}</p>{invite&&<div className="invite-banner"><ShieldCheck/> دعوة شركة موثقة</div>}<form onSubmit={submit}>{mode==="signup"&&<label className="auth-field"><span>الاسم الكامل</span><div><UserRound/><Input value={fullName} onChange={e=>setFullName(e.target.value)} autoComplete="name" required/></div></label>}<label className="auth-field"><span>البريد الإلكتروني</span><div><Mail/><Input dir="ltr" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></div></label>{mode!=="forgot"&&<label className="auth-field"><span>كلمة المرور</span><div><KeyRound/><Input dir="ltr" type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="signup"?"new-password":"current-password"} required/><button type="button" className="password-eye" onClick={()=>setShow(!show)} aria-label="إظهار كلمة المرور">{show?<EyeOff/>:<Eye/>}</button></div>{mode==="signup"&&<small>8 أحرف على الأقل وتحتوي على رقم</small>}</label>}<Button className="primary-action" type="submit" disabled={busy}>{busy?"جاري التنفيذ...":mode==="signup"?"إنشاء الحساب":mode==="forgot"?"إرسال رابط الاسترجاع":"دخول"} <ArrowLeft/></Button></form>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success-banner">{notice}</p>}<div className="auth-switches">{portal==="owner"&&mode!=="forgot"&&<button onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"ما عندكش حساب؟ أنشئ حساب":"عندك حساب؟ سجل دخول"}</button>}{mode==="login"&&<button onClick={()=>setMode("forgot")}>نسيت كلمة المرور</button>}{mode==="forgot"&&<button onClick={()=>setMode("login")}>رجوع لتسجيل الدخول</button>}</div><div className="privacy-note"><ShieldCheck/><span>بيانات الدخول لا تظهر للشركات ولا لأي شخص يمسح بطاقة دورني.</span></div></section></main>}

export default function LoginPage(){return <Suspense fallback={<main className="loading-screen" dir="rtl">جاري تحميل الدخول...</main>}><LoginContent/></Suspense>}
