import { createHash } from "node:crypto";
import { z } from "zod";
import { createServerSupabase } from "@/lib/supabase/server";
import { getAccountContext } from "@/lib/server/account";
import { json,requireUser,UnauthorizedError } from "@/lib/server/http";

const loginSchema=z.object({email:z.string().trim().email().max(254),password:z.string().min(8).max(128),portal:z.enum(["owner","partner"]).default("owner")});
const signupSchema=z.object({fullName:z.string().trim().min(2).max(100),email:z.string().trim().email().max(254),password:z.string().min(8).max(128).regex(/[A-Za-z]/).regex(/\d/),portal:z.enum(["owner","partner"]).default("owner"),companyName:z.string().trim().min(2).max(160).optional(),companyType:z.enum(["INSURANCE","CORPORATE","DISTRIBUTOR","OTHER"]).optional(),registrationNumber:z.string().trim().max(80).optional(),inviteToken:z.string().min(32).max(200).optional()}).superRefine((value,ctx)=>{if(value.portal==="partner"&&!value.inviteToken&&!value.companyName)ctx.addIssue({code:z.ZodIssueCode.custom,path:["companyName"],message:"اسم الشركة مطلوب"});});
const emailSchema=z.object({email:z.string().trim().email().max(254)});
const passwordSchema=z.object({password:z.string().min(8).max(128).regex(/[A-Za-z]/).regex(/\d/)});
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");

export async function GET(_request:Request,{params}:{params:Promise<{action:string}>}){const {action}=await params;if(action!=="context")return json({error:"NOT_FOUND"},404);try{const {supabase}=await requireUser();return json(await getAccountContext(supabase));}catch(error){return json({error:error instanceof UnauthorizedError?"UNAUTHORIZED":"تعذر تحديد نوع الحساب"},error instanceof UnauthorizedError?401:500);}}

export async function POST(request:Request,{params}:{params:Promise<{action:string}>}){const {action}=await params;try{
  if(action==="login"){const value=loginSchema.parse(await request.json());const supabase=await createServerSupabase();const {error}=await supabase.auth.signInWithPassword({email:value.email.toLowerCase(),password:value.password});if(error)return json({error:"البريد أو كلمة المرور غير صحيحة"},401);const context=await getAccountContext(supabase);if(value.portal==="partner"&&!context.partnerRole&&!context.internalRole){await supabase.auth.signOut({scope:"local"});return json({error:"هذا الحساب غير مربوط بشركة في دورني"},403);}return json({ok:true,context});}
  if(action==="signup"){const value=signupSchema.parse(await request.json());const email=value.email.toLowerCase();const supabase=await createServerSupabase();if(value.inviteToken){const {data:invitation,error}=await supabase.rpc("preview_partner_invitation",{p_token_hash:digest(value.inviteToken)});if(error||!invitation)return json({error:"دعوة الشركة غير صالحة أو انتهت"},400);if(String(invitation.email).toLowerCase()!==email)return json({error:"استخدم نفس البريد المكتوب في دعوة الشركة"},400);}const isPartner=value.portal==="partner"||Boolean(value.inviteToken);const callback=new URL("/auth/callback",request.url);callback.searchParams.set("next",isPartner?"/partner":"/app");const {data,error}=await supabase.auth.signUp({email,password:value.password,options:{data:{full_name:value.fullName,account_type:isPartner?"partner":"owner",company_name:value.companyName??null,company_type:value.companyType??"CORPORATE",registration_number:value.registrationNumber||null},emailRedirectTo:callback.toString()}});if(error)return json({error:error.message.includes("already")?"البريد مسجل من قبل":"تعذر إنشاء الحساب"},400);if(value.inviteToken&&data.session){const claimed=await supabase.rpc("claim_partner_invitation",{p_token_hash:digest(value.inviteToken)});if(claimed.error)return json({error:"تم إنشاء الحساب لكن تعذر ربط دعوة الشركة"},400);}else if(isPartner&&data.session){const registered=await supabase.rpc("register_my_partner_organization",{p_name:value.companyName,p_type:value.companyType??"CORPORATE",p_registration_number:value.registrationNumber||null});if(registered.error)return json({error:"تم إنشاء الحساب لكن تعذر إنشاء ملف الشركة"},400);}const response=json({ok:true,needsEmailConfirmation:!data.session,destination:isPartner?"/partner":"/app"},201);if(value.inviteToken&&!data.session)response.cookies.set("dorni_partner_invite",value.inviteToken,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",maxAge:604800,path:"/"});return response;}
  if(action==="forgot-password"){const {email}=emailSchema.parse(await request.json());const supabase=await createServerSupabase();const redirect=new URL("/auth/callback",request.url);redirect.searchParams.set("next","/reset-password");await supabase.auth.resetPasswordForEmail(email.toLowerCase(),{redirectTo:redirect.toString()});return json({ok:true});}
  if(action==="update-password"){const {supabase}=await requireUser();const {password}=passwordSchema.parse(await request.json());const {error}=await supabase.auth.updateUser({password});if(error)throw error;return json({ok:true});}
  return json({error:"NOT_FOUND"},404);
}catch(error){if(error instanceof UnauthorizedError)return json({error:"UNAUTHORIZED"},401);if(error instanceof z.ZodError)return json({error:"راجع البيانات: البريد صحيح وكلمة المرور 8 أحرف وفيها رقم"},400);console.error("Account action failed",action,error);return json({error:"تعذر إكمال العملية توا"},500);}}
