"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {RefreshCw} from "lucide-react";
import {requestJson,errorMessage} from "@/lib/client-api";
import {InstitutionalWorkspace} from "@/components/institutional-workspace";
import {DorniBrand} from "@/components/dorni-brand";
type Context={memberships:{organizationId:string;organizationName:string;institutionalEnabled:boolean;organizationStatus:string}[]};
export default function InstitutionalPage(){const [context,setContext]=useState<Context|null>(null),[selected,setSelected]=useState(""),[error,setError]=useState("");useEffect(()=>{requestJson<Context>("/api/auth/context").then(c=>{setContext(c);const eligible=c.memberships.filter(m=>m.institutionalEnabled&&m.organizationStatus==="ACTIVE");if(eligible.length===1)setSelected(eligible[0].organizationId);}).catch(e=>setError(errorMessage(e)));},[]);if(error)return <main className="loading-screen" dir="rtl"><p>{error}</p><Link href="/partner">الرجوع لبوابة الشركة</Link></main>;if(!context)return <main className="loading-screen" dir="rtl"><RefreshCw className="spin"/> جاري التحميل…</main>;const eligible=context.memberships.filter(m=>m.institutionalEnabled&&m.organizationStatus==="ACTIVE");return <main className="portal-page" dir="rtl"><header className="portal-header"><DorniBrand href="/partner"/><Link href="/partner">بوابة الشركة</Link></header><section className="portal-content"><div className="portal-title"><div><p className="eyebrow">دورني للمؤسسات</p><h1>مساحة المؤسسة الموثقة</h1></div>{eligible.length>1&&<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">اختر المؤسسة</option>{eligible.map(m=><option value={m.organizationId} key={m.organizationId}>{m.organizationName}</option>)}</select>}</div>{selected?<InstitutionalWorkspace organizationId={selected}/>:<div className="empty-state"><h2>لا توجد مؤسسة موثقة مفعّلة لهذا الحساب</h2><p>تفعيل الصلاحيات المؤسسية يتم فقط من إدارة دورني.</p></div>}</section></main>}
